### ISSUE TITLE
 Error: spawn convert ENOENT

### ISSUE THREAD

**Issue by maniprataprana** [jquery/download.jqueryui.com#296]
Hi all,
I facing below error after foll0wing all the steps on this command=>node server.js --console          
Build Cache Cleanup: { cached: 0, deleted: 0 }
Image Cache Cleanup: { cached: 0, deleted: 0 }
Built Packages Cache Cleanup: { cached: 0, deleted: 0 }
Caught exception: Error: spawn convert ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1057:32)
    at child_process.js:1151:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3

Please help  me here.

Not sure how to debug this. I have searched SO and google for the possible solution, but couldn't find any.
The steps given here were not working for the later versions of node and imagemagik.
Also it seem that readme file is not updated.

Thanks

**Comment by rxaviers** [comment]
Do you have ImageMagick installed? If so which version? https://github.com/jquery/download.jqueryui.com#requirements

**Comment by maniprataprana** [comment]
I have  ImageMagick-6.6.9-10 installed on OS X Yosemite

**Comment by rxaviers** [comment]
Ok, it should work for you. We need more info about the reason the spawn process is crashing for you...

**Comment by maniprataprana** [comment]
How do I get that info ?... because all I can see is above error message nothing else

**Comment by rxaviers** [comment]
I'm afraid you'll have to inspect the code where `convert` is spawned, like `lib/themeroller-image.js`, and check the output there. Note that the package for 1.12 makes use of https://github.com/rxaviers/jquery-ui-themeroller instead.
