### ISSUE TITLE
Incorrect "invalid components" error?

### ISSUE THREAD

**Issue by jzaefferer** [jquery/download.jqueryui.com#314]
Found this in syslog, probably one cause of the 50x errors our users are seeing:
```
Jul 13 09:34:14 builder-01 download.jqueryui.com[14014]: User request exception: Error: Builder: invalid components [ "data", "disable-selection", "focusable", "form-reset-mixin", "jquery-1-7", "keycode", "labels", "scroll-parent", "tabbable", "unique-id", "widgets/draggable", "widgets/droppable", "widgets/resizable", "widgets/selectable", "widgets/sortable", "widgets/accordion", "widgets/autocomplete", "widgets/button", "widgets/checkboxradio", "widgets/controlgroup", "widgets/datepicker", "widgets/dialog", "widgets/menu", "widgets/mouse", "widgets/progressbar", "widgets/selectmenu", "widgets/slider", "widgets/spinner", "widgets/tabs", "widgets/tooltip", "effects/effect-blind", "effects/effect-bounce", "effects/effect-clip", "effects/effect-drop", "effects/effect-explode", "effects/effect-fade", "effects/effect-fold", "effects/effect-highlight", "effects/effect-puff", "effects/effect-pulsate", "effects/effect-scale", "effects/effect-shake", "effects/effect-size", "effects/effect-slide", "effects/effect-transfer" ]#012
    at Object.Builder.expandComponents (/var/www/download.jqueryui.com/lib/builder.js:77:10)#012
    at Object.Builder (/var/www/download.jqueryui.com/lib/builder.js:18:25)#012
    at Object.Frontend.create (/var/www/download.jqueryui.com/download.js:118:15)#012
    at /var/www/download.jqueryui.com/server.js:80:22#012
    at IncomingForm.<anonymous> (/var/www/download.jqueryui.com/node_modules/formidable/lib/incoming_form.js:117:9)#012
    at IncomingForm.emit (events.js:104:17)#012
    at IncomingForm._maybeEnd (/var/www/download.jqueryui.com/node_modules/formidable/lib/incoming_form.js:377:8)#012
    at QuerystringParser.parser.onEnd (/var/www/download.jqueryui.com/node_modules/formidable/lib/incoming_form.js:350:10)#012
    at QuerystringParser.end (/var/www/download.jqueryui.com/node_modules/formidable/lib/querystring_parser.js:24:8)#012
    at IncomingMessage.<anonymous> (/var/www/download.jqueryui.com/node_modules/formidable/lib/incoming_form.js:98:30)
```
Since the list of components isn't manually entered anywhere, this is probably a bug.

**Comment by jzaefferer** [comment]
Coming from here: https://github.com/jquery/download.jqueryui.com/blob/master/lib/builder.js#L77

As far as I can tell, this is reject 1.12 components, when it shouldn't even run this code at all for 1.12 builds.

**Comment by jzaefferer** [comment]
This check prevents this (deprecated) builder to run for 1.12: https://github.com/jquery/download.jqueryui.com/blob/master/download.js#L112

Not sure how the wrong component list makes it past that... maybe an issue in the frontend, where the 1.12 component list is incorrectly set for a 1.11 download?

**Comment by jzaefferer** [comment]
So its indeed the combination of 1.11.4 with 1.12 components. I have no idea how that happens and can't spend more time debugging this now.

**Comment by scottgonzalez** [comment]
Is this still an issue?
